### ISSUE TITLE
[bug] 最近提交的更新似乎把 Set/Settings 連同 Configure 一起翻譯為「組態」了。

### ISSUE THREAD

**Issue by hwhsu1231** [bluelovers/idea-l10n-zht#101]
### 問題描述

最近的更新似乎把 Set/Settings 連同 Configure 一起翻譯為「組態」了。

https://github.com/bluelovers/idea-l10n-zht/commit/9bf9ccaa90f63a6f9d9e9d0b2773ba414f883a76

### 版本

* **CLion:** `2023.1`
* **Plugin:** `231.250`

### 擷圖

![image](https://user-images.githubusercontent.com/71438617/229340791-8fb98037-82b6-45f3-8e86-09e47ba3a55a.png)

**Comment by bluelovers** [comment]
https://github.com/bluelovers/idea-l10n-zht/commit/9afa949968fb0ba9d1f01ee5d1a184cd7a7163d8
