### ISSUE TITLE
請問windows的中文字體有辦法更改嗎？

### ISSUE THREAD

**Issue by wubrony2** [bluelovers/idea-l10n-zht#106]
如題，在windows下使用的是新細明體，我覺得比較醜，mac用的字體就很漂亮，我想更改成別的字型，想問修改哪部分的程式碼可以實現？

**Comment by bluelovers** [comment]
![image](https://github.com/bluelovers/idea-l10n-zht/assets/167966/fb853b02-cad7-425d-8b28-58473f4d36ee)

![image](https://github.com/bluelovers/idea-l10n-zht/assets/167966/e37037c9-d1e5-469e-b911-0ff90f49fcd6)

![image](https://github.com/bluelovers/idea-l10n-zht/assets/167966/3f133c39-fa36-4356-856f-b3797f437471)

改這三個地方

**Comment by wubrony2** [comment]
謝謝你，我改第一個地方就有用了！我去網路上找了半天都沒找到方法以為不能改，才跑來這邊問，以為要改動原始碼的部分才有辦法。很抱歉麻煩您了

**Comment by wubrony2** [comment]
不好意思，想請問一下這部分的字體有辦改改嗎？
![](https://imgur.com/Em48sbB.png)
markdown單元格裡的程式碼區塊的字體變得好醜
原始碼長這樣，反而看起來很正常？？
![](https://imgur.com/40XWUc4.png)
這是專業版內建的jupyter功能

**Comment by bluelovers** [comment]
![image](https://github.com/bluelovers/idea-l10n-zht/assets/167966/cee7f454-1ffb-4d85-b168-f95cd895223a)


你有把前面字體設定的那些地方都改過嗎?

我的畫面裏面看起來字體是有效的

**Comment by wubrony2** [comment]
我跟你一樣如果是直接開一般MD檔就沒問題
![](https://imgur.com/t2WJPNQ.png)
但jupyter notebook功能裡面的markdown cell(開的是ipynb檔)
在這個markdown cell裡面的程式碼區塊的字體會變得很醜，但其它地方就很正常
![](https://imgur.com/Em48sbB.png)
順便說一下我用的版本是這個
![](https://imgur.com/99s67j8.png)

**Comment by bluelovers** [comment]
從哪裡打開 jupyter ?

**Comment by wubrony2** [comment]
pycharm裡面內建的，我按ipynb檔就會直接開

**Comment by bluelovers** [comment]
官方不修正的功能

https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004311659-Unable-to-change-font-in-Jupyter-Notebook-in-PyCharm

https://youtrack.jetbrains.com/issue/PY-34684

https://youtrack.jetbrains.com/issue/PY-53404/Rendered-Markdown-font-size-customization-in-Jupyter-Notebook-cells

**Comment by bluelovers** [comment]
但是可以暴力的將這段放進去檔案裏面強制更改

```css
%%html
<style type='text/css'>
* {
    font-family: 'JetBrains Mono';
}
</style>
```

不管是編輯模式還是喧染模式都能看到字體已經套用

![image](https://github.com/bluelovers/idea-l10n-zht/assets/167966/c600577a-6b8d-4b33-9d37-6a3ffbc4a47b)

![image](https://github.com/bluelovers/idea-l10n-zht/assets/167966/80220d4d-29ec-49ec-b005-214fe13f691e)

**Comment by bluelovers** [comment]
順便小提醒 沒事別更新到目前的 2024.2 eap (這版本感覺有BUG)

**Comment by wubrony2** [comment]
![](https://i.imgur.com/XQdi1pB.png)
我貼近去檔案裡好像渲染也沒變.....
我案全部執行也一樣

**Comment by bluelovers** [comment]
你離開焦點的時候 會變成只顯示 `%%html` 嗎?

**Comment by wubrony2** [comment]
不會，它變成這樣顯示![](https://imgur.com/ISQl4Ww.png)

**Comment by bluelovers** [comment]
> 不會，它變成這樣顯示![](https://camo.githubusercontent.com/c7408ebb5be949868478d69de961d5a1c203fcc127fb77520042c4735e935ff3/68747470733a2f2f696d6775722e636f6d2f4953516c3457772e706e67)

那你應該內容有問題
離開焦點的時候 要只剩下 %%html

不過話說 看起來你這次的截圖裡面字體是有變了

試著在文字裡面打 0 更容易看出字形變化

**Comment by wubrony2** [comment]
![](https://imgur.com/byB6ki6.png)
沒有啊，利開焦點以後markdown cell裡面的程式碼區塊一樣是顯示很醜的字型......

**Comment by bluelovers** [comment]
試試看

![image](https://github.com/bluelovers/idea-l10n-zht/assets/167966/ac807603-21f8-4ffc-b751-b7001a19c13a)
