### ISSUE TITLE
無法套用

### ISSUE THREAD

**Issue by softbearlolz** [bluelovers/idea-l10n-zht#108]
Android Studio Ladybug | 2024.2.1 Patch 2
Build #AI-242.23339.11.2421.12550806, built on October 25, 2024
Runtime version: 21.0.3+-12282718-b509.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.0
Kotlin plugin: K2 mode (Beta)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4084M
Cores: 12
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.intellij.zh-tw (242.152)

版本 242.152

套用不了 有顯示打勾 但實際上沒有翻譯

**Comment by bluelovers** [comment]
![image](https://github.com/user-attachments/assets/0388ec91-463c-4011-8921-dbaae21ac3e6)
