### ISSUE TITLE
無法安裝插件

### ISSUE THREAD

**Issue by creamgod45** [bluelovers/idea-l10n-zht#12]
請問現在編譯的版本是 221 EAP?

**Comment by bluelovers** [comment]
https://github.com/bluelovers/idea-l10n-zht/tags

這裡可以找到其他版本

**Comment by bluelovers** [comment]
@creamgod45 增加了新功能 可以用最新版的繁體處理程式來打包其他舊版本

https://github.com/bluelovers/idea-l10n-zht#other-releases
