### ISSUE TITLE
Jetbrains 的應用程式商店顯示不相容於 2022.1 版，但手動透過 jar 安裝可以

### ISSUE THREAD

**Issue by SiongSng** [bluelovers/idea-l10n-zht#17]
![圖片](https://user-images.githubusercontent.com/48402225/163664941-c2ffa770-6d23-448a-a612-9f7af5b609bb.png)

**Comment by SiongSng** [comment]
剛才看到了，抱歉 #7

**Comment by bluelovers** [comment]
https://github.com/bluelovers/idea-l10n-zht/discussions/11
