### ISSUE TITLE
Open 應該翻譯為【開啟】而不是【打開】

### ISSUE THREAD

**Issue by hwhsu1231** [bluelovers/idea-l10n-zht#19]
### 建議

- Open：開啟
- Open Recent：開啟最近

> 參考 VSCode 的翻譯

### 版本

- **CLion:** 2022.1
- **Plugin:** v221.179

### 截圖

![image](https://user-images.githubusercontent.com/71438617/165982423-8e0ecc9a-9e79-4311-8672-e66ece249fba.png)
![image](https://user-images.githubusercontent.com/71438617/165982429-85abcc29-5eb4-43e4-8f7d-07c824e8ada0.png)
![image](https://user-images.githubusercontent.com/71438617/165984069-5832aac3-b16c-4699-8aa7-e3f3eca7dbb8.png)

**Comment by bluelovers** [comment]
https://github.com/bluelovers/idea-l10n-zht/commit/fcf4323e04c322d658b75e9815c489d307e60079
