### ISSUE TITLE
Plugin 應該翻譯為【外掛】而不是【套件】

### ISSUE THREAD

**Issue by hwhsu1231** [bluelovers/idea-l10n-zht#21]
### 建議

- **Plugin:** 插件
- **Kit:** 套件

> 因為 Kit 是翻譯成【套件】，如果 Plugin 也翻譯為【套件】的話會令人混淆，所以我是採用 QtCreator 的翻譯，Plugin = "插件"。
> 雖然 VSCode 中是把 Extension 翻譯為【延伸模組】，但是既然使用不同的英文單詞，我覺得就翻譯為不同的中文。

### 版本

- **CLion:** 2022.1
- **Plugin:** v221.179

### 截圖

![image](https://user-images.githubusercontent.com/71438617/166099808-0b70159c-18b0-45e8-9a60-3cd32757c84f.png)
![image](https://user-images.githubusercontent.com/71438617/166099814-176f562f-b4fd-4577-8b87-7228651c622c.png)

**Comment by ruyut** [comment]
其實 plugin 應該要翻譯為「外掛」

![image](https://user-images.githubusercontent.com/48990452/166623704-82376dfe-9dec-4caf-a630-ac705e94117a.png)

請見：[針對MDN翻譯內容的一般指導原則](https://github.com/mdn/translated-content/blob/main/docs/zh-tw/translation-guide.md)

**Comment by hwhsu1231** [comment]
總之，我覺得 plugin 不應該翻譯為【套件】。
