### ISSUE TITLE
Console 應該翻譯為【主控台】；Terminal 應該翻譯為【終端機】

### ISSUE THREAD

**Issue by hwhsu1231** [bluelovers/idea-l10n-zht#23]
### 建議

- **Console:** 主控台  (original: 控制台)
- **Terminal:** 終端機  (original: 終端)

> 參考 VSCode 翻譯

### 版本

- **CLion:** 2022.1
- **Plugin:** v221.179

### 截圖

![image](https://user-images.githubusercontent.com/71438617/166675350-20dd8825-14a7-4df5-b9f8-482c8b0271da.png)
![image](https://user-images.githubusercontent.com/71438617/166675418-31127609-8963-44d8-be08-3ab613438336.png)
![image](https://user-images.githubusercontent.com/71438617/166675275-8ca66d78-b54c-42c3-869f-80968227da86.png)

**Comment by bluelovers** [comment]
終端機 vs 終端

少一個字 應該沒差
