### ISSUE TITLE
無法手動安裝至最新版本

### ISSUE THREAD

**Issue by WongIong** [bluelovers/idea-l10n-zht#28]
![image](https://user-images.githubusercontent.com/36799194/175081233-1724df18-db37-4966-b590-32527a763aa0.png)

**Comment by WongIong** [comment]
那我要在哪裡下載221版本？
我是從主頁那個按鈕下的，zh.jar

**Comment by bluelovers** [comment]
@WongIong https://github.com/bluelovers/idea-l10n-zht#other-releases

**Comment by WongIong** [comment]
沒有找到221.5787這個版本
我是個新手

**Comment by bluelovers** [comment]
@WongIong 只要找 221 開頭的最高版本就可以

![image](https://user-images.githubusercontent.com/167966/175398162-6b3a1df7-ce4c-4d7a-85bc-ebb69f85c6ef.png)

![image](https://user-images.githubusercontent.com/167966/175398335-7b063824-0c94-4895-881d-8cd7343491b8.png)

![image](https://user-images.githubusercontent.com/167966/175398504-b83734dc-ab3b-4511-b258-12189088d267.png)

![image](https://user-images.githubusercontent.com/167966/175398552-4f2198a6-6805-4138-98a2-373034cdc850.png)

![image](https://user-images.githubusercontent.com/167966/175398615-9dcb8be7-fdeb-4019-a272-5a16a7c7e4bf.png)

https://github.com/bluelovers/idea-l10n-zht/raw/v221.179/plugin-dev-out/zh.jar

**Comment by WongIong** [comment]
後面的我之前已經設定了~
謝謝, 能用了!
