### ISSUE TITLE
不好意思我按github的下載但安裝不成功

### ISSUE THREAD

**Issue by nike01705** [bluelovers/idea-l10n-zht#29]
![messageImage_1658122387216](https://user-images.githubusercontent.com/108004693/179450981-2844661a-2c4e-4ae8-a6b1-5bdbec5c6a49.jpg)

**Comment by ruyut** [comment]
版本問題，請先嘗試更新 IDE
更新方式：上方選單列 Help > Check for Updates...

![image](https://user-images.githubusercontent.com/48990452/179456405-5e45a81e-266c-4fb1-87c3-426bd434a03f.png)

**Comment by bluelovers** [comment]
@nike01705 要安裝對應版本

請參考
https://github.com/bluelovers/idea-l10n-zht/issues/26

**Comment by bluelovers** [comment]
現在已經有編譯好的 212 版在 git 上
https://github.com/bluelovers/idea-l10n-zht/tree/v212/plugin-dev-out
