### ISSUE TITLE
Does not work with the latest version of IntelliJ IDEA (IntelliJ IDEA 2022.1.3)

### ISSUE THREAD

**Issue by Microtribute** [bluelovers/idea-l10n-zht#31]
![image](https://user-images.githubusercontent.com/46481195/184259792-51477d03-ace5-4235-baa3-2a52497674ff.png)

**Comment by bluelovers** [comment]
ur ide need install plugin v221 not v223

**Comment by Microtribute** [comment]
謝謝!!!
