### ISSUE TITLE
能不能在 Release/Tag 中為所有版本提供已經打包好的 zh.jar？

### ISSUE THREAD

**Issue by hwhsu1231** [bluelovers/idea-l10n-zht#32]
如果從首頁的 [Install](https://github.com/bluelovers/idea-l10n-zht#install) 點擊【install from Github】連結的話，下載的會是最新版本的 zh.jar。

![image](https://user-images.githubusercontent.com/71438617/202464081-903f172a-df00-403f-9ad3-a2cf94c51340.png)

但是我目前安裝的 CLion 是 `2022.2.4` 版本，當我將下載好的 zh.jar 拖移到程式介面後，結果卻出現以下錯誤訊息：

![image](https://user-images.githubusercontent.com/71438617/202465292-6fa21de9-ee3c-473c-bcf4-49038e52aaa8.png)

從 [Other Releases](https://github.com/bluelovers/idea-l10n-zht#other-releases) 中可以看到，如果要使用其他版本的翻譯包，必須自行打包，但是這樣有點不方便。能不能請作者在 Release/Tag 中為所有版本提供已經打包好的 zh.jar？

![image](https://user-images.githubusercontent.com/71438617/202497330-8d936c16-df43-47f5-8661-f2d8b69fc9c7.png)

**Comment by bluelovers** [comment]
參考設定這個
https://github.com/bluelovers/idea-l10n-zht/discussions/25


如果你還是希望手動下載
則請看這個檔案
https://github.com/bluelovers/idea-l10n-zht/blob/master/plugin-dev-out/updatePlugins.xml

**Comment by bluelovers** [comment]
順便有個小技巧
只要 將 `https://github.com/bluelovers/idea-l10n-zht/raw/v223.35/plugin-dev-out/zh.jar`

當中的 `v223.35` 換成 `v223` 就會自動得到該系列的最後一個版本
