### ISSUE TITLE
Explorer 應該翻譯成【檔案總管】。

### ISSUE THREAD

**Issue by hwhsu1231** [bluelovers/idea-l10n-zht#36]
### 建議

- **Explorer:** 檔案總管

### 版本

- **CLion:** `2022.2.4`
- **Plugin:** `v222.202`

### 擷圖

![image](https://user-images.githubusercontent.com/71438617/202842285-97137c5d-34ea-4481-8099-99fa4c07c5cf.png)

**Comment by bluelovers** [comment]
語言包內不存在可以設定這個翻譯的設定

**Comment by hwhsu1231** [comment]
@bluelovers 

所以這個問題是不是要回報給上游的【[官方簡體中文語言包](https://plugins.jetbrains.com/plugin/13710-chinese-simplified-language-pack----)】？

**Comment by bluelovers** [comment]
> @bluelovers
> 
> 所以這個問題是不是要回報給上游的【[官方簡體中文語言包](https://plugins.jetbrains.com/plugin/13710-chinese-simplified-language-pack----)】？

恩

**Comment by hwhsu1231** [comment]
@bluelovers 

我發現在目前最新的版本中，【Explorer】的字串已經可以翻譯了。

### 建議

* **英文字串:** Explorer
* **當前翻譯:** 瀏覽器
* **建議翻譯:** 檔案總管

### 版本

* **CLion:** `2023.1`
* **IntelliJ:** `2023.1`
* **Plugin:** `231.250`

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/229271526-293d07a8-3a4c-4d28-b45b-f747b772ab8c.png)
