### ISSUE TITLE
Rename 應該翻譯為【重新命名】而不是【重命名】。

### ISSUE THREAD

**Issue by hwhsu1231** [bluelovers/idea-l10n-zht#39]
### 建議

- **Rename:** 重新命名

### 版本

- **CLion:** `2022.2.4`
- **Plugin:** `v222.202`

### 擷圖

![image](https://user-images.githubusercontent.com/71438617/203748027-8ac2cd8c-6594-43de-af0a-ecd9bd2952b5.png)
![image](https://user-images.githubusercontent.com/71438617/203748063-1f94bed8-8047-4f63-83d6-24c3856d9bc7.png)

**Comment by bluelovers** [comment]
話說 你可以考慮用 toolbox 安裝兩次 ide 其中一個不要裝語言包就可以同時截圖中英文

**Comment by hwhsu1231** [comment]
感謝告知，不過我暫時沒這個打算。
