### ISSUE TITLE
Function 應該翻譯為【函式】而不是【函數】。

### ISSUE THREAD

**Issue by hwhsu1231** [bluelovers/idea-l10n-zht#41]
### 建議

- **Function:** 函式

就我所知，台灣將 Function 翻譯成【函式】似乎是為了與數學上的【函數】作區別。

### 版本

- **CLion:** `2022.2.4`
- **Plugin:** `222.202`

### 擷圖

![image](https://user-images.githubusercontent.com/71438617/204079042-59422cd2-ddf9-4838-a9ce-26988c5cb308.png)

**Comment by bluelovers** [comment]
https://ithelp.ithome.com.tw/questions/10002441
