### ISSUE TITLE
Cloud 建議翻譯為【雲端】而不是【云】。

### ISSUE THREAD

**Issue by hwhsu1231** [bluelovers/idea-l10n-zht#62]
### 建議

* **英文字串:** Cloud
* **當前翻譯:** 云
* **建議翻譯:** 雲端

結合 #61 的【Connection】，【Cloud Connection】應該翻譯為【雲端連線】。

### 版本

* **CLion:** `2022.3`
* **Plugin:** `223.228`

### 擷圖

![image](https://user-images.githubusercontent.com/71438617/208225972-52997edb-7fd4-403a-b8e5-436c091d1fec.png)

**Comment by hwhsu1231** [comment]
@bluelovers 為什麼只是把	「云」改成「雲」呢？

**Comment by bluelovers** [comment]
基本上偏向於 不加字 避免錯誤的轉換
