### ISSUE TITLE
Reference 建議翻譯為【參考】。

### ISSUE THREAD

**Issue by hwhsu1231** [bluelovers/idea-l10n-zht#68]
### 建議

* **英文字串:** Reference
* **當前翻譯:** 引用
* **建議翻譯:** 參考

以 C/C++ 的概念來說，有一個東西叫做【Reference】，我記得：

* 大陸翻譯: 引用
* 台灣翻譯: 參考

因此我建議這裡翻譯為【參考】。

### 版本

* **CLion:** `2022.3`
* **Plugin:** `223.228`

### 擷圖

![image](https://user-images.githubusercontent.com/71438617/208409852-347aa936-daa7-431f-9488-10da9456cd25.png)

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/216478621-ea539a7a-3a60-4f95-ab37-263aca0b0a54.png)

https://zh.m.wikipedia.org/zh-tw/%E5%8F%83%E7%85%A7

**Comment by hwhsu1231** [comment]
@bluelovers 

其實我不太確定【參考】和【參照】之間究竟哪個在意思層面上比較合適。但是以下是我傾向於前者（參考）的原因：

* 雖然我也有在其他 C++ 書籍或文章中看到將【Reference】翻譯為【參照】，但是我看過的部分大多翻譯為【參考】。

* 我在 Google 搜尋引擎中嘗試輸入【傳參照呼叫】...等關鍵字，結果 Google 卻反問我【你是不是要查: 傳參考呼叫】

* 平常日常用語幾乎都是使用【參考】，例如：參考書、參考線、參考資料、參考文獻...等等。

![2023-02-03_17-09-28](https://user-images.githubusercontent.com/71438617/216966098-a6e3effa-bf6e-4810-a209-b232d3957f8b.png)

**Comment by hwhsu1231** [comment]
在 Google 上搜尋【參照線】，結果也是反問我【你是不是要查: 參考線】

![image](https://user-images.githubusercontent.com/71438617/216968994-941c097b-e590-4bac-9627-60d10453145c.png)

**Comment by hwhsu1231** [comment]
就舉【Interface】的翻譯為例。

- 大陸翻譯:【前端的 Interface】翻作【界面】，【後端的 Interface】翻作【接口】。
- 台灣翻譯: 無論【前端】或【後端】都統一翻作【介面】。

台灣這邊的翻譯有個優點就是，不會出現把本應是【前端的 Interface】翻成【後端的 Interface】，反之亦然。

不過【Function】的翻譯卻有剛好相反。

* 大陸翻譯: 無論【數學】或【電腦科學】都統一翻作【函數】。
* 台灣翻譯:【數學的 Function】翻作【函數】，【電腦科學的 Function】翻作【函式】。

Errr......
