### ISSUE TITLE
套件市場中 IDE不相容

### ISSUE THREAD

**Issue by ruyut** [bluelovers/idea-l10n-zht#7]
在 JetBrains Marketplace 中無法安裝套件
顯示 IDE不相容 (WebStorm 2021.3.1, IntelliJ IDEA 2021.3.1)
![圖片](https://user-images.githubusercontent.com/48990452/150646353-5cf89ae6-8a3e-4f17-9ad6-070d9de9aefb.png)

**Comment by bluelovers** [comment]
因為我刪除了 市集 上面的版本 重新上傳 所以 現在對於使用者而言 插件是不存在的
然後 預設所有不存在的插件 都會被當作不相容
等到審核通過之後 就會正常顯示

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/150651060-801634cb-4554-44f5-b55c-9f8e7bbfa82e.png)

![image](https://user-images.githubusercontent.com/167966/150651074-a61ede9d-4f06-4f72-ba04-f58df6d61c5a.png)

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/152058970-12abbc86-27ad-4e82-9bbe-4e3cb17f71d1.png)

好像上傳時發生了點BUG 導致現在官方市集那邊需要解決問題後 才能夠讓 plugin 成功顯示

**Comment by bluelovers** [comment]
https://github.com/bluelovers/idea-l10n-zht/discussions/11
